change build-kernel to uki * now I using uki images for the kernel for security reason * also makes configure secure boot an using refind easier * downside requires recompile kernel to change cmdline *(if I change kernel cmdline is when updatind the kernel so no big deal there)
Signed-off-by: Gonçalo Negrier Duarte <gonegrier.duarte@gmail.com>

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -5,16 +5,21 @@ kernel_ver=$(eselect kernel list | cat | grep "*" | cut -b 15-17)
 kernel_selected=$(eselect kernel list | cat | grep "*" | cut -d '-' -f2)
 BOOT_KERNEL=$(echo "$(uname -r)" | cut -c -12)
 verify_printk_true=$(zcat /proc/config.gz | grep 'CONFIG_PRINTK_TIME=y')
+#Pls edit this for your drives and also lines 250-264
 NVME_1=/dev/disk/by-uuid/a00bc72b-4433-4ca2-8989-d63e268091bd
-#$NVME_2=
+NVME_2=/dev/disk/by-uuid/6f27386f-5ede-4ef8-aacd-c40c772d0084
 EXTERNAL_HDD=/dev/disk/by-uuid/9299af67-f63a-4d1c-bd63-082fc90d55a8
+#
 #Disable TPM LUKS ENROLL for people that dosent use LUKS encrypted drives
 LUKS_DISABLE=0
+#pls edit this if using /boot
+ESP=/efi
 
 #Force run with root
 if [ "$EUID" -ne 0 ]; then
-	echo "Please run as root"
-	exit
+	echo "Running with root..."
+  [ $(which doas) ] && exec doas bash "$0" "$@" || exec sudo bash "$0" "$@"
+	exit $?
 fi
 
 #Funtions
@@ -219,7 +224,7 @@ compile_kernel() {
 	sleep 2
 	make LLVM=1 LLVM_IAS=1 install
 
-	echo "Move Kernel to /boot/efi/gentoo folder"
+	echo "Moving Kernel to ${ESP}/efi/gentoo folder"
 	read -n 1 -s -r -p "Press any key to continue..." && echo
 }
 
@@ -233,21 +238,12 @@ build_initramfs() {
 	dracut -f --regenerate-all
 
 	#Not using unfied kernel image
-	#mv /boot/{System.map-*,config-*,vmlinuz-*,refind_linux.conf} /boot/EFI/gentoo
+	#mv ${ESP}/{System.map-*,config-*,vmlinuz-*,refind_linux.conf} ${ESP}/EFI/gentoo
 
 	#Using unfied Kernel Image
-	#mkdir /boot/cleanup
-	#mv /boot/{System.map-*,config-*,vmlinuz-*,refind_linux.conf} /boot/cleanup
-	mv /boot/EFI/Linux/* /boot/EFI/gentoo
-	rm -r /boot/EFI/Linux
+	#mkdir ${ESP}/cleanup
+	#mv ${ESP}/{System.map-*,config-*,vmlinuz-*,refind_linux.conf} ${ESP}/cleanup
 
-	echo Done!
-	read -n 1 -s -r -p "Press any key to continue..." && echo
-}
-
-sign_kernel() {
-	sbctl sign /boot/EFI/gentoo/vmlinuz-$kernel_selected-*
-	sbctl sign-all
 	echo Done!
 	read -n 1 -s -r -p "Press any key to continue..." && echo
 }
@@ -256,8 +252,10 @@ tpm_enroll_luks() {
 	#Fix when running the 6 option
 	if [[ $LUKS_DISABLE -eq 0 ]]; then
 		clevis luks unbind -d $NVME_1 -s 1
+    clevis luks unbind -d $NVME_2 -s 1
 		clevis luks unbind -d $EXTERNAL_HDD -s 1
 		clevis luks bind -d $NVME_1 tpm2 '{"pcr_bank":"sha256","pcr_ids":"0,1,2,3,5,6,7"}'
+		clevis luks bind -d $NVME_2 tpm2 '{"pcr_bank":"sha256","pcr_ids":"0,1,2,3,5,6,7"}'
 		clevis luks bind -d $EXTERNAL_HDD tpm2 '{"pcr_bank":"sha256","pcr_ids":"0,1,2,3,5,6,7"}'
 	else
 		echo && echo "$(tput bold)This option is disable set LUKS_DISABLE to 0$(tput sgr0)" && echo
@@ -275,8 +273,9 @@ start_menu() {
 	echo "3 - Copy kernel config"
 	echo "4 - Compile the kernel"
 	echo "5 - Rebuil out of tree kernel modules"
-	echo "6 - Rebuil initramfs"
-	#echo "7 - Sign Kernel Secure Boot"
+  # When using uki rebuild initramfs and cmdline is done when kernel compiles
+  # Not using uki pls uncomment line 235-240 line 319 
+  echo "6 - Rebuil initramfs (not work with uki)"
 	echo "7 - Enroll Disks Luks key in TPM"
 	echo "8 - Run All"
 	echo
@@ -311,10 +310,6 @@ start_menu() {
 		build_initramfs
 		start_menu
 		;;
-		#7)
-		#sign_kernel
-		#start_menu
-		#;;
 	7)
 		tpm_enroll_luks
 		start_menu
@@ -325,8 +320,7 @@ start_menu() {
 		copy_kernel_config
 		compile_kernel
 		rebuild_modules
-		build_initramfs
-		#sign_kernel
+		#build_initramfs
 		echo "Done!!! - Reboot the system"
 		;;
 
